# Generated by Django 5.0.3 on 2024-08-31 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_customuser_is_active_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="TeamSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(auto_now_add=True)),
                ("weekly_points", models.IntegerField(default=0)),
                (
                    "game_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_snapshots",
                        to="api.gameweek",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="snapshot_players", to="api.player"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api.team",
                    ),
                ),
            ],
        ),
    ]
