# Generated by Django 5.0.3 on 2024-09-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_gameweek_teamsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameweek",
            name="week",
            field=models.IntegerField(default=0),
        ),
    ]
