# Generated by Django 5.0.3 on 2024-09-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_gameweek_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="game_week",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.gameweek",
            ),
        ),
    ]
