# Generated by Django 5.0.3 on 2024-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_match_game_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="total_points",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
