# Generated by Django 5.0.3 on 2024-10-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_player_total_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=100)),
                ("team2", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
