# Generated by Django 5.0.3 on 2024-11-15 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_fixture"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fixture",
            unique_together={("team1", "team2")},
        ),
    ]
