# Generated by Django 5.0.3 on 2024-11-15 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_fixture_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="total_points",
            new_name="points",
        ),
    ]
