# Generated by Django 5.0.3 on 2024-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_rename_total_points_player_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="WomensFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team1", models.CharField(max_length=100)),
                ("team2", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
            options={
                "unique_together": {("team1", "team2")},
            },
        ),
    ]
