# Generated by Django 5.0.3 on 2025-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_womensfixture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
    ]
