# Generated by Django 5.0.3 on 2025-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_player_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="MOTM",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="Pen_Saves",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="playergamestats",
            name="MOTM",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playergamestats",
            name="Pen_Saves",
            field=models.IntegerField(default=0),
        ),
    ]
