# Generated by Django 5.0.3 on 2025-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_player_motm_player_pen_saves_playergamestats_motm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team1_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="team2_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="total_points",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
