# Generated by Django 5.2.6 on 2025-09-13 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_match_team1_score_match_team2_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_teams', to='api.player'),
        ),
        migrations.AddField(
            model_name='teamsnapshot',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_snapshots', to='api.player'),
        ),
        migrations.AddIndex(
            model_name='teamsnapshot',
            index=models.Index(fields=['game_week', 'weekly_points'], name='api_teamsna_game_we_19fe1e_idx'),
        ),
    ]
