# Generated by Django 5.2.7 on 2025-10-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_fixture_options_team_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
